// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJiftFCdp9_bAlLbxkjC0t-4f-LLWsEn4',
    appId: '1:60331461282:web:79c38bfbb8c0de56bf25fb',
    messagingSenderId: '60331461282',
    projectId: 'iritin-80577',
    authDomain: 'iritin-80577.firebaseapp.com',
    storageBucket: 'iritin-80577.firebasestorage.app',
    measurementId: 'G-GBYST7PGC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG12HoiTBFLcGj0d1vW7reTlGhx2IQjm0',
    appId: '1:60331461282:android:829ada510fcd1458bf25fb',
    messagingSenderId: '60331461282',
    projectId: 'iritin-80577',
    storageBucket: 'iritin-80577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAspsdq367mKrEf6u7K3q3c1bIa2MWyB1A',
    appId: '1:60331461282:ios:3adaa11798dc3cdcbf25fb',
    messagingSenderId: '60331461282',
    projectId: 'iritin-80577',
    storageBucket: 'iritin-80577.firebasestorage.app',
    iosBundleId: 'com.example.iritin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAspsdq367mKrEf6u7K3q3c1bIa2MWyB1A',
    appId: '1:60331461282:ios:3adaa11798dc3cdcbf25fb',
    messagingSenderId: '60331461282',
    projectId: 'iritin-80577',
    storageBucket: 'iritin-80577.firebasestorage.app',
    iosBundleId: 'com.example.iritin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJiftFCdp9_bAlLbxkjC0t-4f-LLWsEn4',
    appId: '1:60331461282:web:14e19e0d3f029134bf25fb',
    messagingSenderId: '60331461282',
    projectId: 'iritin-80577',
    authDomain: 'iritin-80577.firebaseapp.com',
    storageBucket: 'iritin-80577.firebasestorage.app',
    measurementId: 'G-NYGNX1XJYP',
  );
}
